services:
  stream-webpage:
    build: .
    environment:
      - FRAMERATE=${FRAMERATE:-60}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PORT=${PORT:-8080}
      - STATUS_CRON_SCHEDULE=${STATUS_CRON_SCHEDULE}
      - RESOLUTION=${RESOLUTION:-720p}
      - RTMP_URL=${RTMP_URL:-rtmp://rtmp-server:1935/live/stream}
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - WEBPAGE_URL=${WEBPAGE_URL:-https://google.com}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

  # RTMP server for testing
  rtmp-server:
    image: tiangolo/nginx-rtmp
    profiles: ["dev"]
    ports:
      - "1935:1935"
