# Edge Image Build Workflow
# This workflow builds and pushes the edge image for the Stream Webpage Container on merge to the main branch.
name: Edge Image Build

concurrency:
  group: edge-build

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/zozman/stream-webpage-container

jobs:
  build-image:
    name: Build Edge Image
    uses: ./.github/workflows/docker-multiarch.yaml
    secrets: inherit
    with:
      image: ghcr.io/zozman/stream-webpage-container
      merge_job_name: Build Edge Image
      build_job_name_prefix: Build Edge Image
      tags: |
        type=raw,value=edge
        type=sha
        type=sha,format=long
