# Edge Image Build Workflow
# This workflow builds and pushes the edge image for the Stream Webpage Container on merge to the main branch.
name: Edge Image Build

concurrency:
  group: edge-build

on:
  push:
    branches:
      - main

jobs:
  edge:
    name: Build Edge Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/zozman/stream-webpage-container
          tags: |
            type=raw,value=edge
            type=sha
            type=sha,format=long

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image to GitHub Container Registries
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
